app:
  name: MyApp
  version: 1.0.0
  environment: production

server:
  port: 8080
  host: 0.0.0.0

database:
  host: db.example.com
  port: 5432
  user: myuser
  password: mypassword
  name: mydatabase
